// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mapnificent.proto

/*
Package mapnificent is a generated protocol buffer package.

It is generated from these files:
	mapnificent.proto

It has these top-level messages:
	MapnificentNetwork
*/
package mapnificent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MapnificentNetwork struct {
	Cityid string                     `protobuf:"bytes,1,opt,name=Cityid" json:"Cityid,omitempty"`
	Stops  []*MapnificentNetwork_Stop `protobuf:"bytes,2,rep,name=Stops" json:"Stops,omitempty"`
	Lines  []*MapnificentNetwork_Line `protobuf:"bytes,3,rep,name=Lines" json:"Lines,omitempty"`
}

func (m *MapnificentNetwork) Reset()                    { *m = MapnificentNetwork{} }
func (m *MapnificentNetwork) String() string            { return proto.CompactTextString(m) }
func (*MapnificentNetwork) ProtoMessage()               {}
func (*MapnificentNetwork) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MapnificentNetwork) GetCityid() string {
	if m != nil {
		return m.Cityid
	}
	return ""
}

func (m *MapnificentNetwork) GetStops() []*MapnificentNetwork_Stop {
	if m != nil {
		return m.Stops
	}
	return nil
}

func (m *MapnificentNetwork) GetLines() []*MapnificentNetwork_Line {
	if m != nil {
		return m.Lines
	}
	return nil
}

type MapnificentNetwork_Stop struct {
	Latitude      float64                                 `protobuf:"fixed64,1,opt,name=Latitude" json:"Latitude,omitempty"`
	Longitude     float64                                 `protobuf:"fixed64,2,opt,name=Longitude" json:"Longitude,omitempty"`
	TravelOptions []*MapnificentNetwork_Stop_TravelOption `protobuf:"bytes,3,rep,name=TravelOptions" json:"TravelOptions,omitempty"`
	Name          string                                  `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
}

func (m *MapnificentNetwork_Stop) Reset()                    { *m = MapnificentNetwork_Stop{} }
func (m *MapnificentNetwork_Stop) String() string            { return proto.CompactTextString(m) }
func (*MapnificentNetwork_Stop) ProtoMessage()               {}
func (*MapnificentNetwork_Stop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *MapnificentNetwork_Stop) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *MapnificentNetwork_Stop) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *MapnificentNetwork_Stop) GetTravelOptions() []*MapnificentNetwork_Stop_TravelOption {
	if m != nil {
		return m.TravelOptions
	}
	return nil
}

func (m *MapnificentNetwork_Stop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MapnificentNetwork_Stop_TravelOption struct {
	Stop         uint32 `protobuf:"varint,1,opt,name=Stop" json:"Stop,omitempty"`
	TravelTime   uint32 `protobuf:"varint,2,opt,name=TravelTime" json:"TravelTime,omitempty"`
	StayTime     uint32 `protobuf:"varint,3,opt,name=StayTime" json:"StayTime,omitempty"`
	Line         string `protobuf:"bytes,4,opt,name=Line" json:"Line,omitempty"`
	WalkDistance uint32 `protobuf:"varint,5,opt,name=WalkDistance" json:"WalkDistance,omitempty"`
}

func (m *MapnificentNetwork_Stop_TravelOption) Reset()         { *m = MapnificentNetwork_Stop_TravelOption{} }
func (m *MapnificentNetwork_Stop_TravelOption) String() string { return proto.CompactTextString(m) }
func (*MapnificentNetwork_Stop_TravelOption) ProtoMessage()    {}
func (*MapnificentNetwork_Stop_TravelOption) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

func (m *MapnificentNetwork_Stop_TravelOption) GetStop() uint32 {
	if m != nil {
		return m.Stop
	}
	return 0
}

func (m *MapnificentNetwork_Stop_TravelOption) GetTravelTime() uint32 {
	if m != nil {
		return m.TravelTime
	}
	return 0
}

func (m *MapnificentNetwork_Stop_TravelOption) GetStayTime() uint32 {
	if m != nil {
		return m.StayTime
	}
	return 0
}

func (m *MapnificentNetwork_Stop_TravelOption) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *MapnificentNetwork_Stop_TravelOption) GetWalkDistance() uint32 {
	if m != nil {
		return m.WalkDistance
	}
	return 0
}

type MapnificentNetwork_Line struct {
	LineId    string                              `protobuf:"bytes,1,opt,name=LineId" json:"LineId,omitempty"`
	LineTimes []*MapnificentNetwork_Line_LineTime `protobuf:"bytes,2,rep,name=LineTimes" json:"LineTimes,omitempty"`
	Name      string                              `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
}

func (m *MapnificentNetwork_Line) Reset()                    { *m = MapnificentNetwork_Line{} }
func (m *MapnificentNetwork_Line) String() string            { return proto.CompactTextString(m) }
func (*MapnificentNetwork_Line) ProtoMessage()               {}
func (*MapnificentNetwork_Line) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *MapnificentNetwork_Line) GetLineId() string {
	if m != nil {
		return m.LineId
	}
	return ""
}

func (m *MapnificentNetwork_Line) GetLineTimes() []*MapnificentNetwork_Line_LineTime {
	if m != nil {
		return m.LineTimes
	}
	return nil
}

func (m *MapnificentNetwork_Line) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MapnificentNetwork_Line_LineTime struct {
	Interval uint32 `protobuf:"varint,1,opt,name=Interval" json:"Interval,omitempty"`
	Start    uint32 `protobuf:"varint,2,opt,name=Start" json:"Start,omitempty"`
	Stop     uint32 `protobuf:"varint,3,opt,name=Stop" json:"Stop,omitempty"`
	Weekday  uint32 `protobuf:"varint,4,opt,name=Weekday" json:"Weekday,omitempty"`
}

func (m *MapnificentNetwork_Line_LineTime) Reset()         { *m = MapnificentNetwork_Line_LineTime{} }
func (m *MapnificentNetwork_Line_LineTime) String() string { return proto.CompactTextString(m) }
func (*MapnificentNetwork_Line_LineTime) ProtoMessage()    {}
func (*MapnificentNetwork_Line_LineTime) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1, 0}
}

func (m *MapnificentNetwork_Line_LineTime) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *MapnificentNetwork_Line_LineTime) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *MapnificentNetwork_Line_LineTime) GetStop() uint32 {
	if m != nil {
		return m.Stop
	}
	return 0
}

func (m *MapnificentNetwork_Line_LineTime) GetWeekday() uint32 {
	if m != nil {
		return m.Weekday
	}
	return 0
}

func init() {
	proto.RegisterType((*MapnificentNetwork)(nil), "mapnificent.MapnificentNetwork")
	proto.RegisterType((*MapnificentNetwork_Stop)(nil), "mapnificent.MapnificentNetwork.Stop")
	proto.RegisterType((*MapnificentNetwork_Stop_TravelOption)(nil), "mapnificent.MapnificentNetwork.Stop.TravelOption")
	proto.RegisterType((*MapnificentNetwork_Line)(nil), "mapnificent.MapnificentNetwork.Line")
	proto.RegisterType((*MapnificentNetwork_Line_LineTime)(nil), "mapnificent.MapnificentNetwork.Line.LineTime")
}

func init() { proto.RegisterFile("mapnificent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0x4e, 0x29, 0xf0, 0xc3, 0x40, 0x0f, 0xff, 0xc6, 0x98, 0xa6, 0x31, 0x86, 0x10, 0x0f, 0x5c,
	0x6c, 0xa2, 0xde, 0xbc, 0xea, 0x85, 0x88, 0x98, 0x2c, 0x24, 0x9c, 0x57, 0x58, 0xcd, 0x0a, 0x6c,
	0x9b, 0x32, 0x62, 0x78, 0x11, 0x1f, 0xc9, 0x97, 0xf0, 0x11, 0x7c, 0x09, 0x33, 0xbb, 0x74, 0x59,
	0xe2, 0xa5, 0xa7, 0xce, 0x37, 0x33, 0xdf, 0xd7, 0x99, 0x6f, 0x16, 0xfe, 0xaf, 0x45, 0xae, 0xd5,
	0x8b, 0x9a, 0x4b, 0x8d, 0x69, 0x5e, 0x64, 0x98, 0xb1, 0x8e, 0x97, 0xea, 0x7f, 0x37, 0x80, 0x3d,
	0x1e, 0xf0, 0x58, 0xe2, 0x47, 0x56, 0x2c, 0xd9, 0x29, 0x34, 0xef, 0x14, 0xee, 0xd4, 0x22, 0x0e,
	0x7a, 0xc1, 0xa0, 0xcd, 0xf7, 0x88, 0xdd, 0x42, 0x63, 0x82, 0x59, 0xbe, 0x89, 0x6b, 0xbd, 0x70,
	0xd0, 0xb9, 0xbe, 0x48, 0x7d, 0xf9, 0xbf, 0x3a, 0x29, 0x35, 0x73, 0x4b, 0x21, 0xee, 0x48, 0x69,
	0xb9, 0x89, 0xc3, 0x6a, 0x5c, 0x6a, 0xe6, 0x96, 0x92, 0x7c, 0xd5, 0xa0, 0x4e, 0x2a, 0x2c, 0x81,
	0xd6, 0x48, 0xa0, 0xc2, 0xf7, 0x85, 0x34, 0xa3, 0x05, 0xdc, 0x61, 0x76, 0x06, 0xed, 0x51, 0xa6,
	0x5f, 0x6d, 0xb1, 0x66, 0x8a, 0x87, 0x04, 0x9b, 0x41, 0x34, 0x2d, 0xc4, 0x56, 0xae, 0x9e, 0x72,
	0x54, 0x99, 0x2e, 0xc7, 0xb8, 0xaa, 0xb2, 0x42, 0xea, 0x33, 0xf9, 0xb1, 0x0e, 0x63, 0x50, 0x1f,
	0x8b, 0xb5, 0x8c, 0xeb, 0xc6, 0x29, 0x13, 0x27, 0x9f, 0x01, 0x74, 0xfd, 0x2e, 0x6a, 0x22, 0x21,
	0x33, 0x73, 0xc4, 0xed, 0x2e, 0xe7, 0x00, 0xb6, 0x67, 0xaa, 0xd6, 0x76, 0xe0, 0x88, 0x7b, 0x19,
	0xda, 0x75, 0x82, 0x62, 0x67, 0xaa, 0xa1, 0xa9, 0x3a, 0x4c, 0x7a, 0xe4, 0x4c, 0xf9, 0x53, 0x8a,
	0x59, 0x1f, 0xba, 0x33, 0xb1, 0x5a, 0xde, 0xab, 0x0d, 0x0a, 0x3d, 0x97, 0x71, 0xc3, 0x70, 0x8e,
	0x72, 0xc9, 0x4f, 0x60, 0x89, 0x74, 0x61, 0xfa, 0x0e, 0xdd, 0x85, 0x2d, 0x62, 0x0f, 0xd0, 0xa6,
	0x88, 0x7e, 0x52, 0x5e, 0xf9, 0xb2, 0xca, 0xa5, 0xd2, 0x92, 0xc5, 0x0f, 0x7c, 0x67, 0x4d, 0xe8,
	0x59, 0xf3, 0x06, 0xad, 0xb2, 0x81, 0x36, 0x1c, 0x6a, 0x94, 0xc5, 0x56, 0xac, 0xf6, 0xce, 0x38,
	0xcc, 0x4e, 0xe8, 0xa9, 0x89, 0x02, 0xf7, 0xc6, 0x58, 0xe0, 0x7c, 0x0c, 0x3d, 0x1f, 0x63, 0xf8,
	0x37, 0x93, 0x72, 0xb9, 0x10, 0x3b, 0x63, 0x47, 0xc4, 0x4b, 0xf8, 0xdc, 0x34, 0x2f, 0xfe, 0xe6,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xe3, 0xae, 0xff, 0x06, 0x03, 0x00, 0x00,
}
