// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mapnificent.proto

/*
Package mapnificent is a generated protocol buffer package.

It is generated from these files:
	mapnificent.proto

It has these top-level messages:
	MapnificentNetwork
*/
package mapnificent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MapnificentNetwork struct {
	Cityid string                     `protobuf:"bytes,1,opt,name=Cityid" json:"Cityid,omitempty"`
	Stops  []*MapnificentNetwork_Stop `protobuf:"bytes,2,rep,name=Stops" json:"Stops,omitempty"`
	Lines  []*MapnificentNetwork_Line `protobuf:"bytes,3,rep,name=Lines" json:"Lines,omitempty"`
}

func (m *MapnificentNetwork) Reset()                    { *m = MapnificentNetwork{} }
func (m *MapnificentNetwork) String() string            { return proto.CompactTextString(m) }
func (*MapnificentNetwork) ProtoMessage()               {}
func (*MapnificentNetwork) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MapnificentNetwork) GetCityid() string {
	if m != nil {
		return m.Cityid
	}
	return ""
}

func (m *MapnificentNetwork) GetStops() []*MapnificentNetwork_Stop {
	if m != nil {
		return m.Stops
	}
	return nil
}

func (m *MapnificentNetwork) GetLines() []*MapnificentNetwork_Line {
	if m != nil {
		return m.Lines
	}
	return nil
}

type MapnificentNetwork_Stop struct {
	Latitude      float64                                 `protobuf:"fixed64,1,opt,name=Latitude" json:"Latitude,omitempty"`
	Longitude     float64                                 `protobuf:"fixed64,2,opt,name=Longitude" json:"Longitude,omitempty"`
	TravelOptions []*MapnificentNetwork_Stop_TravelOption `protobuf:"bytes,3,rep,name=TravelOptions" json:"TravelOptions,omitempty"`
	Name          string                                  `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
}

func (m *MapnificentNetwork_Stop) Reset()                    { *m = MapnificentNetwork_Stop{} }
func (m *MapnificentNetwork_Stop) String() string            { return proto.CompactTextString(m) }
func (*MapnificentNetwork_Stop) ProtoMessage()               {}
func (*MapnificentNetwork_Stop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *MapnificentNetwork_Stop) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *MapnificentNetwork_Stop) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *MapnificentNetwork_Stop) GetTravelOptions() []*MapnificentNetwork_Stop_TravelOption {
	if m != nil {
		return m.TravelOptions
	}
	return nil
}

func (m *MapnificentNetwork_Stop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MapnificentNetwork_Stop_TravelOption struct {
	Stop         int32  `protobuf:"varint,1,opt,name=Stop" json:"Stop,omitempty"`
	TravelTime   int32  `protobuf:"varint,2,opt,name=TravelTime" json:"TravelTime,omitempty"`
	StayTime     int32  `protobuf:"varint,3,opt,name=StayTime" json:"StayTime,omitempty"`
	Line         string `protobuf:"bytes,4,opt,name=Line" json:"Line,omitempty"`
	WalkDistance int32  `protobuf:"varint,5,opt,name=WalkDistance" json:"WalkDistance,omitempty"`
}

func (m *MapnificentNetwork_Stop_TravelOption) Reset()         { *m = MapnificentNetwork_Stop_TravelOption{} }
func (m *MapnificentNetwork_Stop_TravelOption) String() string { return proto.CompactTextString(m) }
func (*MapnificentNetwork_Stop_TravelOption) ProtoMessage()    {}
func (*MapnificentNetwork_Stop_TravelOption) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0, 0}
}

func (m *MapnificentNetwork_Stop_TravelOption) GetStop() int32 {
	if m != nil {
		return m.Stop
	}
	return 0
}

func (m *MapnificentNetwork_Stop_TravelOption) GetTravelTime() int32 {
	if m != nil {
		return m.TravelTime
	}
	return 0
}

func (m *MapnificentNetwork_Stop_TravelOption) GetStayTime() int32 {
	if m != nil {
		return m.StayTime
	}
	return 0
}

func (m *MapnificentNetwork_Stop_TravelOption) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *MapnificentNetwork_Stop_TravelOption) GetWalkDistance() int32 {
	if m != nil {
		return m.WalkDistance
	}
	return 0
}

type MapnificentNetwork_Line struct {
	LineId    string                              `protobuf:"bytes,1,opt,name=LineId" json:"LineId,omitempty"`
	LineTimes []*MapnificentNetwork_Line_LineTime `protobuf:"bytes,2,rep,name=LineTimes" json:"LineTimes,omitempty"`
	Name      string                              `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
}

func (m *MapnificentNetwork_Line) Reset()                    { *m = MapnificentNetwork_Line{} }
func (m *MapnificentNetwork_Line) String() string            { return proto.CompactTextString(m) }
func (*MapnificentNetwork_Line) ProtoMessage()               {}
func (*MapnificentNetwork_Line) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *MapnificentNetwork_Line) GetLineId() string {
	if m != nil {
		return m.LineId
	}
	return ""
}

func (m *MapnificentNetwork_Line) GetLineTimes() []*MapnificentNetwork_Line_LineTime {
	if m != nil {
		return m.LineTimes
	}
	return nil
}

func (m *MapnificentNetwork_Line) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MapnificentNetwork_Line_LineTime struct {
	Interval int32 `protobuf:"varint,1,opt,name=Interval" json:"Interval,omitempty"`
	Start    int32 `protobuf:"varint,2,opt,name=Start" json:"Start,omitempty"`
	Stop     int32 `protobuf:"varint,3,opt,name=Stop" json:"Stop,omitempty"`
	Weekday  int32 `protobuf:"varint,4,opt,name=Weekday" json:"Weekday,omitempty"`
}

func (m *MapnificentNetwork_Line_LineTime) Reset()         { *m = MapnificentNetwork_Line_LineTime{} }
func (m *MapnificentNetwork_Line_LineTime) String() string { return proto.CompactTextString(m) }
func (*MapnificentNetwork_Line_LineTime) ProtoMessage()    {}
func (*MapnificentNetwork_Line_LineTime) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1, 0}
}

func (m *MapnificentNetwork_Line_LineTime) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *MapnificentNetwork_Line_LineTime) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *MapnificentNetwork_Line_LineTime) GetStop() int32 {
	if m != nil {
		return m.Stop
	}
	return 0
}

func (m *MapnificentNetwork_Line_LineTime) GetWeekday() int32 {
	if m != nil {
		return m.Weekday
	}
	return 0
}

func init() {
	proto.RegisterType((*MapnificentNetwork)(nil), "mapnificent.MapnificentNetwork")
	proto.RegisterType((*MapnificentNetwork_Stop)(nil), "mapnificent.MapnificentNetwork.Stop")
	proto.RegisterType((*MapnificentNetwork_Stop_TravelOption)(nil), "mapnificent.MapnificentNetwork.Stop.TravelOption")
	proto.RegisterType((*MapnificentNetwork_Line)(nil), "mapnificent.MapnificentNetwork.Line")
	proto.RegisterType((*MapnificentNetwork_Line_LineTime)(nil), "mapnificent.MapnificentNetwork.Line.LineTime")
}

func init() { proto.RegisterFile("mapnificent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x4d, 0x29, 0x45, 0x18, 0xf0, 0xe0, 0xc6, 0x98, 0xa6, 0x31, 0x86, 0x10, 0x0f, 0x5c, 0x6c,
	0xa2, 0xde, 0xbc, 0xea, 0x85, 0x88, 0x98, 0x2c, 0x24, 0x9c, 0x57, 0x58, 0xcd, 0x0a, 0x6c, 0x9b,
	0x32, 0x62, 0xf8, 0x11, 0x3f, 0xc9, 0x9f, 0xf0, 0x13, 0xfc, 0x09, 0x33, 0xbb, 0x74, 0x59, 0xe2,
	0xa5, 0xa7, 0xce, 0x9b, 0x99, 0xf7, 0x3a, 0xf3, 0x66, 0xe1, 0x64, 0x25, 0x72, 0xad, 0x5e, 0xd5,
	0x4c, 0x6a, 0x4c, 0xf3, 0x22, 0xc3, 0x8c, 0xb5, 0xbd, 0x54, 0xef, 0x27, 0x02, 0xf6, 0xb4, 0xc7,
	0x23, 0x89, 0x9f, 0x59, 0xb1, 0x60, 0x67, 0xd0, 0xb8, 0x57, 0xb8, 0x55, 0xf3, 0x38, 0xe8, 0x06,
	0xfd, 0x16, 0xdf, 0x21, 0x76, 0x07, 0xd1, 0x18, 0xb3, 0x7c, 0x1d, 0xd7, 0xba, 0x61, 0xbf, 0x7d,
	0x73, 0x99, 0xfa, 0xf2, 0xff, 0x75, 0x52, 0x6a, 0xe6, 0x96, 0x42, 0xdc, 0xa1, 0xd2, 0x72, 0x1d,
	0x87, 0xd5, 0xb8, 0xd4, 0xcc, 0x2d, 0x25, 0xf9, 0xae, 0x41, 0x9d, 0x54, 0x58, 0x02, 0xcd, 0xa1,
	0x40, 0x85, 0x1f, 0x73, 0x69, 0x46, 0x0b, 0xb8, 0xc3, 0xec, 0x1c, 0x5a, 0xc3, 0x4c, 0xbf, 0xd9,
	0x62, 0xcd, 0x14, 0xf7, 0x09, 0x36, 0x85, 0xe3, 0x49, 0x21, 0x36, 0x72, 0xf9, 0x9c, 0xa3, 0xca,
	0x74, 0x39, 0xc6, 0x75, 0x95, 0x15, 0x52, 0x9f, 0xc9, 0x0f, 0x75, 0x18, 0x83, 0xfa, 0x48, 0xac,
	0x64, 0x5c, 0x37, 0x4e, 0x99, 0x38, 0xf9, 0x0a, 0xa0, 0xe3, 0x77, 0x51, 0x13, 0x09, 0x99, 0x99,
	0x23, 0x6e, 0x77, 0xb9, 0x00, 0xb0, 0x3d, 0x13, 0xb5, 0xb2, 0x03, 0x47, 0xdc, 0xcb, 0xd0, 0xae,
	0x63, 0x14, 0x5b, 0x53, 0x0d, 0x4d, 0xd5, 0x61, 0xd2, 0x23, 0x67, 0xca, 0x9f, 0x52, 0xcc, 0x7a,
	0xd0, 0x99, 0x8a, 0xe5, 0xe2, 0x41, 0xad, 0x51, 0xe8, 0x99, 0x8c, 0x23, 0xc3, 0x39, 0xc8, 0x25,
	0xbf, 0x81, 0x25, 0xd2, 0x85, 0xe9, 0x3b, 0x70, 0x17, 0xb6, 0x88, 0x3d, 0x42, 0x8b, 0x22, 0xfa,
	0x49, 0x79, 0xe5, 0xab, 0x2a, 0x97, 0x4a, 0x4b, 0x16, 0xdf, 0xf3, 0x9d, 0x35, 0xa1, 0x67, 0xcd,
	0x3b, 0x34, 0xcb, 0x06, 0xda, 0x70, 0xa0, 0x51, 0x16, 0x1b, 0xb1, 0xdc, 0x39, 0xe3, 0x30, 0x3b,
	0xa5, 0xa7, 0x26, 0x0a, 0xdc, 0x19, 0x63, 0x81, 0xf3, 0x31, 0xf4, 0x7c, 0x8c, 0xe1, 0x68, 0x2a,
	0xe5, 0x62, 0x2e, 0xb6, 0xc6, 0x8e, 0x88, 0x97, 0xf0, 0xa5, 0x61, 0x5e, 0xfc, 0xed, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x17, 0x1c, 0x62, 0x38, 0x06, 0x03, 0x00, 0x00,
}
